name: Build Windows ARM64 Debug

on:
  workflow_dispatch:

jobs:
  build-windows-arm64-debug:
    name: Debug Windows ARM64
    runs-on: windows-11-arm

    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Cache Flutter
        uses: actions/cache@v4
        with:
          path: |
            ~\AppData\Local\Pub\Cache
            build
          key: flutter-windows-arm64-${{ hashFiles('pubspec.lock') }}

      - name: Setup flutter
        uses: subosito/flutter-action@v2
        with:
          channel: master
          flutter-version-file: pubspec.yaml

      - name: Apply Patch
        shell: pwsh
        run: lib/scripts/patch.ps1 windows

      - name: Set and Extract version
        shell: pwsh
        run: lib/scripts/build.ps1

      - name: Get dependencies
        run: flutter pub get

      - name: Build Windows ARM64 Debug
        run: |
          flutter build windows --debug --dart-define-from-file=pili_release.json

      - name: Upload Debug Build
        uses: actions/upload-artifact@v7
        with:
          archive: true
          name: Windows-arm64-debug
          path: build/windows/arm64/runner/Debug/
